Create professional-development.md
mattermost/mattermost-handbook pull request #1019
Opened 2022-04-08 13:32 UTC by jasonblais

Moving resource from Google Docs to handbook.

Source: https://docs.google.com/document/d/1sGsbbz1ir3XOGsf3FDySt5P1BpWW6KDqh1qBk1tmAdA/edit#

2022-04-22 13:27 UTC, jasonblais commented
@wiersgallak @justinegeffen friendly reminder on the PR review :)

2022-04-22 13:28 UTC, wiersgallak commented
Hi @jasonblais Just curious what prompted adding this to the handbook?

2022-04-22 13:34 UTC, jasonblais commented
@wiersgallak I've received questions about prof development tracks in the PM team, so I thought to add the information to the handbook

2022-04-22 13:40 UTC, wiersgallak commented
@jasonblais Thanks for clarifying.  The original doc was not fully finished, so I just added a note into the first section explaining it a bit.

2022-04-23 14:45 UTC, justinegeffen approved these changes, later dismissed

2022-04-25 11:36 UTC, jasonblais commented
Thanks @wiersgallak, where did you add the note to? Sorry I couldn't find it in the GitHub PR or the doc,

2022-04-27 15:27 UTC, wiersgallak requested changes
Seems I forgot to submit these last time.  Sorry for the delay.

2022-04-27 15:27 UTC, wiersgallak commented on operations/research-and-development/product/professional-development.md
> +This page outlines professional development tracks available to all product team members (Product Managers, Product Designers, Technical Writers, and Product Analytics Engineers)
```suggestion
This page outlines professional development tracks available to all product team members (Product Managers, Product Designers, Technical Writers, and Product Analytics Engineers). 

The courses listed below are suggestions and not all have been validated.  Some topics do not currently have a suggested course yet. If you take a class that is useful, please consider adding it to this list. 
```

2022-07-02 09:09 UTC, justinegeffen approved these changes, later dismissed

2022-07-08 13:58 UTC, wiersgallak approved these changes, later dismissed

2022-07-08 14:00 UTC, justinegeffen commented
Need to add TOC entry.

2022-07-12 19:00 UTC, justinegeffen approved these changes

2022-07-12 19:00 UTC, merged