Update total-rewards.md
mattermost/mattermost-handbook pull request #1084
Opened 2022-09-06 23:10 UTC by iogungbade

#### Summary

2022-09-06 23:10 UTC, iogungbade commented
I added a section on "how we determine compensation".

2022-09-07 22:47 UTC, natalie-hub requested changes
I reviewed feedback/edits with @iogungbade directly, and she'll make changes to this PR.

2022-10-18 23:30 UTC, natalie-hub submitted a review, later dismissed
Looks good, sorry for delay

2022-10-25 13:49 UTC, cwarnermm commented on operations/workplace/people/total-rewards.md
> +- _**Why we align compenstion to the local market**_
```suggestion
- _**Why we align compensation to the local market**_ 
```

2022-10-27 16:05 UTC, justinegeffen approved these changes

2022-10-27 16:11 UTC, justinegeffen commented
/check-cla

2022-10-27 16:11 UTC, justinegeffen commented
/check-cla

2022-10-27 16:13 UTC, merged