Update README.md
mattermost/mattermost-handbook pull request #1236
Opened 2023-07-05 19:13 UTC by yomiadetutu1

Company info update and additional Bamboo info

#### Summary

2023-07-05 19:15 UTC, amyblais approved these changes, later dismissed

2023-07-06 13:08 UTC, lynn915 requested changes
Folks need to sign up to Ruby receptionist (I don't think it's done automatically). Can you check with Hanna on this and then update accordingly. Perhaps adjust to say that if FT Staff wish to be added to the directory, to contact hanna@mattermost.com (or people@mattermost.com)? Thanks!

2023-07-07 14:23 UTC, yomiadetutu1 commented on operations/workplace/people/README.md
> +The official phone number for Mattermost, Inc. is +1 (650) 667-8512. All company phone calls are received via Ruby, our virtual receptionist app, and redirected to the appropriate persons.
```suggestion
The official phone number for Mattermost, Inc. is +1 (650) 667-8512. All company phone calls are received via Ruby, our virtual receptionist app. FT staff that wish to be added to the directory should contact hanna@mattermost.com or hr@mattermost.com. 
```

2023-07-07 14:38 UTC, amyblais commented on operations/workplace/people/README.md
> +The official phone number for Mattermost, Inc. is +1 (650) 667-8512. All company phone calls are received via Ruby, our virtual receptionist app. FT staff that wish to be added to the directory shoul
```suggestion
The official phone number for Mattermost, Inc. is +1 (650) 667-8512. All company phone calls are received via Ruby, our virtual receptionist app. Full-time staff members who wish to be added to the directory should contact hanna@mattermost.com or hr@mattermost.com. 
```

2023-07-07 15:25 UTC, amyblais approved these changes

2023-07-07 17:15 UTC, lynn915 approved these changes

2023-07-07 17:16 UTC, merged