Update Payment Facilities
mattermost/mattermost-handbook pull request #129
Opened 2020-04-08 19:48 UTC by ialorro

Deleted Transferwise from list of "Facilities not accepted at this time" @TQuock

#### Summary

2020-04-08 19:48 UTC, mattermod commented
Thanks @ialorro for the pull request!

 Per the [**CONTRIBUTING.md**](https://github.com/mattermost/platform/blob/master/CONTRIBUTING.md#submitting-a-pull-request) file displayed when you created this pull request, we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**

This is a standard procedure for many open source projects. Your form should be processed within 24 hours and reviewers for your pull request will be able to proceed.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2020-04-08 19:51 UTC, TQuock requested changes
Are we also going to add additional language as to who qualifies for Tranferswise?

2020-04-12 11:30 UTC, justinegeffen submitted a review, later dismissed
Looks good to me, thank you!

2020-04-13 20:42 UTC, jasonblais commented
/check-cla

2020-04-13 20:42 UTC, jasonblais commented
@ialorro heads up on the question from Tim above

2020-04-14 20:30 UTC, ialorro commented
Thank you @jasonblais ! This was resolved in pull request #136.

2020-04-14 20:34 UTC, jasonblais commented
Great! @TQuock if you can help approve if the changes look good, given #136

2020-04-29 07:44 UTC, justinegeffen commented
Following up on this, @TQuock, are you happy for this to be merged? :)

2020-05-15 15:12 UTC, TQuock commented on company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/how-to-get-paid.md
> +_Example 1_: A staff member named John Smith is located in Spain and signed a consulting agreement with Mattermost, Inc. under his surname, John Smith must have the following banking institution setu
```suggestion
_Example 1_: A staff member named John Smith is located in Spain and signed a consulting agreement with Mattermost, Inc. under his surname, John Smith will need the following banking institution setup:
```

2020-05-15 15:13 UTC, TQuock commented on company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/how-to-get-paid.md
> +_Example 2_: A staff member named John Smith is located in Spain and signed a consulting agreement with Mattermost, Inc. under his LLC titled Better Coding, John Smith must have the following banking
```suggestion
_Example 2_: A staff member named John Smith is located in Spain and signed a consulting agreement with Mattermost, Inc. under his LLC titled Better Coding, John Smith will need the following banking institution setup:
```

2020-05-15 15:16 UTC, TQuock commented on company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/how-to-get-paid.md
>  The person or legal entity the bank account is registered to must be in the name of the contracting individual/entity.
```suggestion
The person or legal entity the bank account is registered to will need to be in the name of the contracting individual/entity.
```

2020-05-15 15:23 UTC, TQuock commented on company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/how-to-get-paid.md
>  If you provide information for your banking institution, your invoice and/or expense reimbursements will be made through Bill.com. As noted above, Mattermost requires banking information from a prima
```suggestion
If you provide information for your banking institution, your invoice and/or expense reimbursements will be made through Bill.com. As noted above, Mattermost needs banking information from a primary banking institution to be able to make reimbursements through Bill.com. Approved expense reports will follow our [Expense reimbursement policy](https://handbook.mattermost.com/company/how-to-guides-for-staff/how-to-spend-company-money/how-to-use-expensify#expense-reimbursement-policy).
```

2020-05-15 15:26 UTC, TQuock commented on company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/how-to-get-paid.md
>  The person or legal entity the bank account is registered to must be in the name of the contracting individual/entity.
@ialorro - can you please check my suggestions and make sure that you agree? If you are good, I'll commit these

2020-05-27 13:35 UTC, ialorro commented
duplicate pull request - resolved in #136

2020-05-27 13:35 UTC, closed without merging

2020-05-27 15:19 UTC, TQuock commented
@ialorro did all the updates make it to the other commit?

2020-05-27 15:21 UTC, ialorro commented
@TQuock I believe so, this was the first pull request I created (not really knowing how to use GitHub) and then I created #136, which had all the edits needed for this section.

2020-05-27 15:25 UTC, TQuock commented
Thanks for the clarification. Issue is closed on my end

All the best,

*Tim Quock *
Director of Accounting
tim@mattermost.com | LinkedIn
<https://www.linkedin.com/in/timothy-quock-23300628/> | mattermost.com | google
calendar availability <https://calendly.com/matters/30min-1>

O: (650) 667-8512
C: (925) 878-1338



*"Train people well enough so they can leave, treat people well enough so
they don't want to" - Richard Branson *





On Wed, May 27, 2020 at 8:22 AM ialorro <notifications@github.com> wrote:

> @TQuock <https://github.com/TQuock> I believe so, this was the first pull
> request I created (not really knowing how to use GitHub) and then I created
> #136 <https://github.com/mattermost/mattermost-handbook/pull/136>, which
> had all the edits needed for this section.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mattermost/mattermost-handbook/pull/129#issuecomment-634735944>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMPAKUFIMPAJVXQSP2M47RTRTUVZ7ANCNFSM4MEF7VCA>
> .
>