Update formal-review-process.md
mattermost/mattermost-handbook pull request #1291
Opened 2023-11-07 01:08 UTC by yomiadetutu1

Updated page to reflect Lattice

#### Summary

2023-11-07 13:58 UTC, cwarnermm submitted a review, later dismissed
Feedback provided inline. Approving.

2023-11-07 13:58 UTC, cwarnermm commented on operations/workplace/people/performance-reviews-50/formal-review-process.md
> +All FT staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **cho
```suggestion
All full-time staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **choose peer reviewers** from the email notification -OR- click the **Select your peer reviewers** task from your Lattice Home page and search for the peers you'd like to nominate. (Note that Lattice pulls its information directly from BambooHR, so legal names will appear in Lattice. If you can't find a peer, please reach out to hr@mattermost.com). On the nomination page, enter the names of the peers you would like to nominate. Review and Confirm nominations by clicking **submit nominations**. We recommend selecting 3-6 peers who can effectively provide feedback on achievements and performance over the past 6 months. Peer nomination selections will be sent to your manager to be finalized. More information on peer nominations is available [here](https://help.lattice.com/hc/en-us/articles/1500001692902-Nominate-Peer-Reviewers-for-Yourself). 
```

2023-11-07 13:58 UTC, cwarnermm commented on operations/workplace/people/performance-reviews-50/formal-review-process.md
> +Once your direct report has completed their nominations, Managers will receive an email and a task in your Lattice home page inbox. You are able to either (a) approve your direct report's nominations
```suggestion
Once your direct report has completed their nominations, Managers will receive an email and a task in your Lattice home page inbox. You are able to either (a) approve your direct report's nominations and immediately send feedback requests to their peer selection, or (b) edit their nominations or add new peers for additional feedback. You can find more information on how to approve your direct reports' peer nominations [here](https://help.lattice.com/hc/en-us/articles/1500001692742-Approve-Your-Direct-Report-s-Peer-Selection). Depending on the role, part-time staff and community members may be solicited to provide feedback in addition to the peer panel selected in Lattice. Once complete, your requests will be scheduled to be sent when the feedback stage starts. Managers may return to this page to send more requests up until the end of the feedback stage. More information for managers on managing the peer selection process is available [here](https://cloud.scorm.com/ScormEngineInterface/defaultui/player/modern.html?configuration=db1M4iPRqeQcV5M7WEvXeR548xreqOrdBfArCusspmFNak_ADJYNngS4sDh3tatitixq2pK56M4ismKY6pGxKFiSJwoc_RMzaLmfg4Orl-taMYTOGgoiqN7_BQOf_4gsnGXazYQNTvQQCm-TJaCY1GLMORukVcukS7mKtH2eDi4DZ8BLS2d_bz5cIK0FGjaasCG6eRal8CY89VULtdgkzMAeMDLfHK0FSpUAik6ssQWzH2o4kJXtEAD8DUyXIE2vMoFVtcWQiQSD-RQ2YQS4SUPct2_cAALcy_lID7dplGN4A5SS_VooWwYKmbW_ImAVf0d1B_yIn_Wh6bIBQwR14UIs8nRIfJp4RYjp44Mvwt6V91K-r3vnYUl0glsburdcjT_LDskdNVXdQ6mUKiPhYQ&preventRightClick=false&cc=en_US&cache=21.1.29.480&playerConfUrl=j&package=4FUGRO2eEOyBQAZP2finOVivEu2TdjeQ6cDnrisganACU6vl5LGF6TqYZ_w9VxSkYld_2FKIQQc_eHyCjhxgA1JaEyUw3rYSzv1r4Qwz_stAvAkbDhJUTA&redirectUrl=https%3A%2F%2Flatticeuniversity.lattice.com%2Fcollections%2Fbf3046c4-d8b0-11ed-a471-06c0361096e5%3Frefresh_status%3Dtrue&registration=URU6tIU2GtP0JEIop33AIAPQ7P9NFOOYbvmvbI8gVfRjLPf7MrV7m7QpMzaDrRbTE_y_Ins1o7Te6K_jBkBohg0DCuNsz6LUxVSs_WcMuJcgXIPlo2sQT8jddmwMOisDwLsZRkhYxvE0HUWLzW4Ii6qRS5Xn5DtM-bTuQI0PNVROx6jz&tracking=true&forceReview=false&player=modern&ts=20231106234140).
```

2023-11-07 17:35 UTC, lynn915 requested changes
@yomiadetutu1 can you update the recommended number of reviewers to be 3-5? 

Also, for this part, can you update it to: 
Staff who have received peer feedback requests will receive an email and a task on their Lattice home page. To complete the request, click **give feedback**. You may decline the request if you don't have feedback to share; however, staff are encouraged to provide feedback when selected as a peer reviewer. Peer reviews help give managers a fuller picture by removing potential blindspots on how their direct reports are performing as it relates to their AORs, goals and growth opportunities, which ultimately helps your peers improve performance and growth potential at Mattermost.

2023-11-08 13:31 UTC, yomiadetutu1 commented on operations/workplace/people/performance-reviews-50/formal-review-process.md
> +All FT staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **cho
```suggestion
All FT staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **choose peer reviewers** from the email notification -OR- click the **Select your peer reviewers** task from your Lattice Home page and search for the peers you'd like to nominate. (Note that Lattice pulls its information directly from BambooHR, so legal names will appear in Lattice. If you can't find a peer, please reach out to hr@mattermost.com). On the nomination page, enter the names of the peers you would like to nominate. Review and Confirm nominations by clicking **submit nominations**. We recommend selecting 3-5 peers who can effectively provide feedback on achievements and performance over the past 6 months. Peer nomination selections will be sent to your manager to be finalized. More information on peer nominations is available [here](https://help.lattice.com/hc/en-us/articles/1500001692902-Nominate-Peer-Reviewers-for-Yourself). 
```

2023-11-08 13:33 UTC, yomiadetutu1 commented on operations/workplace/people/performance-reviews-50/formal-review-process.md
> +Staff who have received peer feedback requests will receive an email and a task on their Lattice home page. To complete the request, click **give feedback**. Peers may decline the request based on ba
```suggestion
Staff who have received peer feedback requests will receive an email and a task on their Lattice home page. To complete the request, click **give feedback**. You may decline the request if you don't have feedback to share; however, staff are encouraged to provide feedback when selected as a peer reviewer. Peer reviews help give managers a fuller picture by removing potential blindspots on how their direct reports are performing as it relates to their AORs, goals and growth opportunities, which ultimately helps your peers improve performance and growth potential at Mattermost.  
```

2023-11-08 15:57 UTC, lynn915 requested changes
@yomiadetutu1 - can you please update this to 3-5 (not 6)
"We recommend selecting 3-6 peers who can effectively provide feedback on achievements and performance over the past 6 months."

For comp review, can you update to approval by CFO and CEO (there is no longer a VP Finance).

2023-11-08 19:28 UTC, yomiadetutu1 commented on operations/workplace/people/performance-reviews-50/formal-review-process.md
> +All compensation changes require approval of the VP of Finance and the CEO.
```suggestion
All compensation changes require approval of the CFO and the CEO.
```

2023-11-08 19:29 UTC, yomiadetutu1 commented on operations/workplace/people/performance-reviews-50/formal-review-process.md
> +All FT staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **cho
```suggestion
All FT staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **choose peer reviewers** from the email notification -OR- click the **Select your peer reviewers** task from your Lattice Home page and search for the peers you'd like to nominate. (Note that Lattice pulls its information directly from BambooHR, so legal names will appear in Lattice. If you can't find a peer, please reach out to hr@mattermost.com). On the nomination page, enter the names of the peers you would like to nominate. Review and Confirm nominations by clicking **submit nominations**. We recommend selecting 3-5 peers who can effectively provide feedback on achievements and performance over the past 6 months. Peer nomination selections will be sent to your manager to be finalized. More information on peer nominations is available [here](https://help.lattice.com/hc/en-us/articles/1500001692902-Nominate-Peer-Reviewers-for-Yourself). 
```

2023-11-09 13:20 UTC, yomiadetutu1 commented on operations/workplace/people/performance-reviews-50/formal-review-process.md
> +All FT staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **cho
```suggestion
All FT staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **choose peer reviewers** from the email notification -OR- click the **Select your peer reviewers** task from your Lattice Home page and search for the peers you'd like to nominate. (Note that Lattice pulls its information directly from BambooHR, so legal names will appear in Lattice. If you can't find a peer, please reach out to hr@mattermost.com). On the nomination page, enter the names of the peers you would like to nominate. Review and Confirm nominations by clicking **submit nominations**. We recommend selecting 3-5 peers who can effectively provide feedback on achievements and performance over the past 6 months. Peer nomination selections will be sent to your manager to be finalized. More information on peer nominations is available [here](https://help.lattice.com/hc/en-us/articles/1500001692902-Nominate-Peer-Reviewers-for-Yourself). 
```

2023-11-09 13:25 UTC, yomiadetutu1 commented on operations/workplace/people/performance-reviews-50/formal-review-process.md
> +All FT staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **cho
```suggestion
All FT staff participating in the review cycle will receive a notification via email as well as a task on your Lattice home page asking you to nominate peers for feedback. To get started, click **choose peer reviewers** from the email notification -OR- click the **Select your peer reviewers** task from your Lattice Home page and search for the peers you'd like to nominate. (Note that Lattice pulls its information directly from BambooHR, so legal names will appear in Lattice. If you can't find a peer, please reach out to hr@mattermost.com). On the nomination page, enter the names of the peers you would like to nominate. Review and Confirm nominations by clicking **submit nominations**. We recommend selecting 3-5 peers who can effectively provide feedback on achievements and performance over the past 6 months. Peer nomination selections will be sent to your manager to be finalized. More information on peer nominations is available [here](https://help.lattice.com/hc/en-us/articles/1500001692902-Nominate-Peer-Reviewers-for-Yourself). 
```

2023-11-22 15:07 UTC, lynn915 approved these changes

2023-11-22 15:09 UTC, cwarnermm approved these changes

2023-11-22 15:09 UTC, merged