Update new-staff-performance-review.md
mattermost/mattermost-handbook pull request #1292
Opened 2023-11-07 01:52 UTC by yomiadetutu1

Updated to reflect Lattice

#### Summary

2023-11-07 13:59 UTC, cwarnermm submitted a review, later dismissed
Feedback provided inline. Approving.

2023-11-07 13:59 UTC, cwarnermm commented on operations/workplace/people/performance-reviews-50/new-staff-performance-review.md
> +* Log in to **Lattice &gt; Performance**. On your Lattice home page, complete the request to select those who will make up the peer panel for the new staff member. For new hires who are people manage
```suggestion
* Log in to **Lattice > Performance**. On your Lattice home page, complete the request to select those who will make up the peer panel for the new staff member. For new hires who are people managers, you may also request upward feedback from their direct reports. We've already provided questions for you to use, so you don't need to worry about customizing them. Note that only full-time Staff are included in the Lattice platform. If you however wish to solicit feedback from part-time Staff or from a community member, you may do so by entering their email address.
```

2023-11-07 18:16 UTC, lynn915 requested changes
Hey @yomiadetutu1 can you remove this, "For new hires who are people managers, you may also request upward feedback from their direct reports. We've already provided questions for you to use, so you don't need to worry about customizing them." 
Context: the upward feedback template is separate and will go out to eveyone - it doesn't have to be "requested".

2023-11-08 13:36 UTC, yomiadetutu1 commented on operations/workplace/people/performance-reviews-50/new-staff-performance-review.md
> +* Log in to **Lattice &gt; Performance**. On your Lattice home page, complete the request to select those who will make up the peer panel for the new staff member. For new hires who are people manage
```suggestion
* Log in to **Lattice &gt; Performance**. On your Lattice home page, complete the request to select those who will make up the peer panel for the new staff member. Note that only FT Staff are included in the Lattice platform. If you however wish to solicit feedback from PT Staff or from a community member, you may do so by entering their email address.
```

2023-11-08 15:54 UTC, lynn915 approved these changes

2023-11-08 16:31 UTC, cwarnermm approved these changes

2023-11-08 16:31 UTC, merged