Update how-to-create-release-announcements.md
mattermost/mattermost-handbook pull request #130
Opened 2020-04-09 18:55 UTC by amyblais

2020-04-13 22:01 UTC, amyblais commented
- Screenshot quality - resolution. Recommendations: Full size screenshots (no zoom-in, no resizing within GDoc), potentially storing in a TIF file.
 - Lock title even earlier in the process.
 - Make sure we give letter grades on title and feature summary (already in the guidelines, will focus on this even more)
 - Improve description of tick-tock releases
 - Goal of the title is to get admins to upgrade (doesn't always need to follow the guidelines) - will add to our guidelines
 - Screenshot guideline related to showing themes and theme icons

2020-04-16 19:09 UTC, jasonblais approved these changes
For the two outstanding items, should we create a handbook issue to keep track of it? (I know you'll have it in your task list, but handbook issue gives more visibility)

2020-04-16 19:09 UTC, jasonblais commented on operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-screenshots-and-gifs.md
> +When you need to show a particular part of the product, don't crop the image and zoom past 100% to show the functionality.   Screenshots should be full-sized (no zoom-in, no resizing within GDoc), po
```suggestion
When you need to show a particular part of the product, don't crop the image and zoom past 100% to show the functionality. Screenshots should be full-sized (no zoom-in, no resizing within Google Doc), potentially stored in a TIF file. For optimal quality on Mac screenshots, [see this help article](https://graphicdesign.stackexchange.com/questions/30081/highest-quality-website-screenshot/30142#30142).

Example of what not to do: 
```

2020-04-16 19:09 UTC, jasonblais commented on operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
> +   8. One or more people on the team put themselves in the shoes of a system admin responsible for upgrading Mattermost, read through the announcement out loud, clicked on the links, and feel we've m
```suggestion
   8. One or more people on the team put themselves in the shoes of a System Admin responsible for upgrading Mattermost and have read through the announcement out loud, clicked on the links, and feel we've met our [High Standards leadership principle](https://handbook.mattermost.com/company/about-mattermost#leadership-principles)
```

2020-04-16 19:09 UTC, jasonblais requested changes
Meant to request changes

2020-04-16 19:12 UTC, amyblais commented
https://github.com/mattermost/mattermost-handbook/issues/147 for other updates.

2020-04-17 14:37 UTC, jasonblais approved these changes

2020-04-17 14:37 UTC, merged