Lattice Update
mattermost/mattermost-handbook pull request #1316
Opened 2024-01-04 15:34 UTC by yomiadetutu1

2024-01-04 20:03 UTC, amyblais submitted a review, later dismissed

2024-01-04 21:11 UTC, lynn915 requested changes
@yomiadetutu1 

Can you remove "goal tracking" from the list of what we and staff use Lattice for currently? I'm not sure when (if) that will be rolled out, so I think we should hold off on including that for now. Perhaps you can replace that with 1:1s or something? Otherwise, looks good to me!

2024-01-05 00:57 UTC, yomiadetutu1 commented on operations/workplace/people/README.md
> +> * The People team uses Lattice to gain insight across the employee experience, using employee engagement surveys, continuous feedback, 360 reviews, and goal tracking.
```suggestion
> * The People team uses Lattice to gain insight across the employee experience, using employee engagement surveys, continuous feedback, 360 reviews, and goal 1:1s.
```

2024-01-05 00:58 UTC, yomiadetutu1 commented on operations/workplace/people/README.md
> +> * The People team uses Lattice to gain insight across the employee experience, using employee engagement surveys, continuous feedback, 360 reviews, and goal tracking.
```suggestion
> * The People team uses Lattice to gain insight across the employee experience, using employee engagement surveys, continuous feedback, 360 reviews, and 1:1s.
```

2024-01-05 00:59 UTC, yomiadetutu1 commented on operations/workplace/people/README.md
> +> * Staff use Lattice for performance reviews such as 90-day reviews and 360 performance reviews, for engagement and employee experience surveys, and goal tracking.
```suggestion
> * Staff use Lattice for performance reviews such as 90-day reviews and 360 performance reviews, for engagement and employee experience surveys, and 1:1s.
```

2024-01-05 01:43 UTC, lynn915 approved these changes
Looks good to me! Thanks, Yomi!

2024-01-08 13:36 UTC, merged