Updated Planned Time Off Page
mattermost/mattermost-handbook pull request #1363
Opened 2024-06-07 18:09 UTC by yomiadetutu1

2024-06-10 15:08 UTC, lynn915 commented on operations/workplace/people/working-at-mattermost/paid-time-off/README.md
> +There are statutory vacation entitlements in countries where Mattermost has an entity or EOR. At a minimum, staff must use their statutory vacation entitlement each year and it is the responsibility
There may be statutory vacation entitlements in countries where Mattermost has an entity or EOR.

2024-06-10 15:09 UTC, lynn915 commented on operations/workplace/people/working-at-mattermost/paid-time-off/README.md
> +1. Communicate your Paid Time Off (PTO) by booking time off in **Rippling > Time Off > Schedule Time Off**. You can also watch this [short video](https://drive.google.com/file/d/1AmDFbIHGsBTPKg-TTTVl
Communicate your Planned Time Off (PTO).

2024-06-10 15:10 UTC, lynn915 commented on operations/workplace/people/working-at-mattermost/paid-time-off/README.md
> +3. Statutory public holidays for FT Staff in entity and EOR locations (Australia, Canada, Germany, Spain, Sweden, US, UK) are automatically listed in Rippling. *For all FT Staff outside of entity and
please ensure to enter any public holidays in your region of residence in Rippling > Time Off > Public Holiday to distinguish it from Planned Time Off.

2024-06-10 15:15 UTC, lynn915 requested changes
I made a few notes for changes. Once those are updated, this is approved.

2024-06-10 17:30 UTC, yomiadetutu1 commented on operations/workplace/people/working-at-mattermost/paid-time-off/README.md
> +There are statutory vacation entitlements in countries where Mattermost has an entity or EOR. At a minimum, staff must use their statutory vacation entitlement each year and it is the responsibility
```suggestion
There may be statutory vacation entitlements in countries where Mattermost has an entity or EOR. At a minimum, staff must use their statutory vacation entitlement each year and it is the responsibility of managers to ensure that their direct reports are taking the required statutory minimum vacation. We understand there may be circumstances where, due to exceptional operational needs or personal issues, it isn’t possible to use up the full annual statutory vacation entitlement.  Exceptions may be granted for vacation carry over in those situations or where there is a statutory requirement to do so. Statutory vacation day carryover must be approved in advance by your manager, Team MLT, and the People Team. Staff members should work with their managers to discuss a plan for booking any accrued but unused statutory vacation. 
```

2024-06-10 17:32 UTC, yomiadetutu1 commented on operations/workplace/people/working-at-mattermost/paid-time-off/README.md
> +1. Communicate your Paid Time Off (PTO) by booking time off in **Rippling > Time Off > Schedule Time Off**. You can also watch this [short video](https://drive.google.com/file/d/1AmDFbIHGsBTPKg-TTTVl
```suggestion
1. Communicate your Planned Time Off (PTO) by booking time off in **Rippling > Time Off > Schedule Time Off**. You can also watch this [short video](https://drive.google.com/file/d/1AmDFbIHGsBTPKg-TTTVlO6gAxSuLDFv0/view?usp=drive_link) on how to book time off in Rippling. PTO covers any number of things - including vacations, stay-cations, moving days, etc. When submitting vacation requests in Rippling, select "Planned Time Off". PTO is in addition to official public holidays in your region of residence. In some countries where there are statutory vacation requirements, public holidays are a supplementary entitlement.
```

2024-06-10 17:36 UTC, yomiadetutu1 commented on operations/workplace/people/working-at-mattermost/paid-time-off/README.md
> +3. Statutory public holidays for FT Staff in entity and EOR locations (Australia, Canada, Germany, Spain, Sweden, US, UK) are automatically listed in Rippling. *For all FT Staff outside of entity and
```suggestion
3. Statutory public holidays for FT Staff in entity and EOR locations (Australia, Canada, Germany, Spain, Sweden, US, UK) are automatically listed in Rippling. *For all FT Staff outside of entity and EOR locations, please ensure to enter any statutory public holidays taken in your region of residence in Rippling > Time Off > Public Holiday to distinguish it from PTO.* 
```

2024-06-10 17:40 UTC, yomiadetutu1 reviewed
Updated with feedback

2024-06-10 20:50 UTC, lynn915 approved these changes
LGTM

2024-06-17 20:26 UTC, lynn915 approved these changes
Looks good to me

2024-06-17 20:49 UTC, cwarnermm approved these changes

2024-06-17 20:50 UTC, merged