mention BugCrowd as Bug Bounty platform
mattermost/mattermost-handbook pull request #1406
Opened 2024-11-07 14:27 UTC by esarafianou

#### Summary
Updates Hackerone mentions as we transitioned to BugCrowd for a Bug Bounty program.

2024-11-07 14:30 UTC, cwarnermm submitted a review, later dismissed

2024-11-07 19:26 UTC, enzowritescode requested changes

2024-11-07 19:26 UTC, enzowritescode commented on operations/security/product-security/product-vulnerability-process.md
> +The vulnerability has been reported through our [Bug Bounty program running on BugCrowd](https://bugcrowd.com/engagements/mattermost-mbb-public).
Technically it's Bugcrowd and not BugCrowd

2024-11-07 19:26 UTC, enzowritescode commented on operations/security/product-security/working-on-sensitive-prs.md
> + - Security-specific tools and terminology: "HackerOne", "BugCrowd", "CVE", "CVSS", "advisory", "pentest".
"Bugcrowd"

2024-11-08 15:20 UTC, enzowritescode approved these changes

2024-11-08 15:57 UTC, merged