Update metrics-definitions.md
mattermost/mattermost-handbook pull request #166
Opened 2020-04-22 13:20 UTC by wiersgallak

#### Summary

2020-04-22 13:32 UTC, michaelschiffmm submitted a review, later dismissed

2020-04-29 07:45 UTC, justinegeffen commented on operations/business-operations/analytics/metrics-definitions.md
> +Deactivating a user in Mattermost will result in MAU decreasing, as deactivated users are filtered out of the statistic's query.  However, reactivating a user in Mattermost will increase the MAU stat
```suggestion
Deactivating a user in Mattermost will result in MAU decreasing, as deactivated users are filtered out of the statistic's query. However, reactivating a user in Mattermost will increase the MAU statistic. 
```

2020-04-29 07:45 UTC, justinegeffen submitted a review, later dismissed

2020-05-15 11:56 UTC, jasonblais commented
@wiersgallak is this one ready to merge, or should we get Justine and Schiff do a second review?

2020-05-15 13:52 UTC, wiersgallak commented
I think @enelson720 still needs to review.  Here were some notes he provided me when we chatted via MM: 

> I think you have it added to the incorrect section. MAU is the user event-based MAU metric. active_users_montly,  active_users_daily, and active_user_count measures are from security and activity diagnostic telemetry and those are the measures impacted by deactivation. I also acknowledge that there are way too many variations of active users

2020-06-24 07:10 UTC, justinegeffen commented on operations/business-operations/analytics/metrics-definitions.md
>  Currently only a subset of possible events, dubbed "whitelist" events, count towards MAU. The reason only a subset of events are captured is a result of exceeding Segment's \(third-party event loggin
```suggestion
Currently only a subset of possible events, dubbed "whitelist" events, count towards MAU. The reason only a subset of events are captured is a result of exceeding Segment's \(third-party event logging service\) row limit. In the future, event logging will transition to Rudder \(another third-party event logging service\), and the list of events that count towards MAU will become more expansive.
```

2020-06-24 07:11 UTC, justinegeffen commented on operations/business-operations/analytics/metrics-definitions.md
>  * Number of trial license requests via [https://mattermost.com/trial](https://mattermost.com/trial) from Named Accounts or Enterprises with 5,000+ employees, in America, EMEA, Australia or Japan.
```suggestion
* Number of trial license requests via [https://mattermost.com/trial](https://mattermost.com/trial) from Named Accounts or Enterprises with 5,000+ employees, in America, EMEA, Australia, or Japan.
```

2020-07-07 11:28 UTC, justinegeffen commented
@enelson720, following up on this to confirm whether it's ready to merge.

2020-07-20 14:30 UTC, justinegeffen commented on operations/business-operations/analytics/metrics-definitions.md
> +Deactivating a user in Mattermost will result in MAU decreasing, as deactivated users are filtered out of the statistic's query. However, reactivating a user in Mattermost will increase the MAU stati
```suggestion
Deactivating a user in Mattermost will result in MAU decreasing, as deactivated users are filtered out of the statistic's query. However, reactivating a user in Mattermost will increase the MAU statistic.
```

2020-07-20 14:30 UTC, justinegeffen submitted a review, later dismissed

2020-08-06 12:54 UTC, justinegeffen commented
Gentle reminder, @enelson720 and @michaelschiffmm. :)

2020-08-06 14:25 UTC, enelson720 commented
> Gentle reminder, @enelson720 and @michaelschiffmm. :)

Sorry, just saw this. Reviewing now.

2020-08-06 14:29 UTC, enelson720 requested changes
This portion of MAU is for user-level MAU events. The server-level diagnostics send `active_users_monthly` statistics that are impacted by the activating and deactivating of users, but this should not impact the user-level MAU calculation, so I don't believe this would be the correct place to have the callout. Perhaps moving it to the TEDAU section as the process of activating and deactivating users also impacts it as well. @justinegeffen

2020-08-07 20:57 UTC, michaelschiffmm submitted a review, later dismissed

2020-08-08 06:31 UTC, justinegeffen commented
Thanks, @enelson720. I've moved the section as suggested.

One other note is that in some cases the dollar value is presented as "30k" and in others it's "$30k" (as an example). If you are able to review that and confirm whether that is correct or they should all have a $ sign that'd be great. :)

2020-09-10 21:25 UTC, michaelschiffmm submitted a review, later dismissed

2020-11-06 13:57 UTC, justinegeffen commented
hey @enelson720. Just following up on this to find out whether we can merge or should close this PR. :)

2020-11-06 15:20 UTC, enelson720 approved these changes
LGTM

2020-11-06 15:30 UTC, merged