Added section on how to follow features
mattermost/mattermost-handbook pull request #259
Opened 2020-06-04 01:27 UTC by thefactremains

added this section for CS and SA: Stay up to date on feature status updates

#### Summary

2020-06-04 11:35 UTC, jasonblais requested changes
Thanks @thefactremains! Minor suggestions turning the steps into numbered bullets to make the sequence of steps easier to follow.

2020-06-04 11:35 UTC, jasonblais commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
> +For more information on how ProductBoard notifications work [click here](https://help.productboard.com/en/articles/1252670-how-do-notifications-work)
```suggestion
[Learn more about ProductBoard notifications](https://help.productboard.com/en/articles/1252670-how-do-notifications-work)
```

2020-06-04 11:35 UTC, jasonblais commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
> +Staying informed of status changes and comments on a feature is fairly easy to do in ProductBoard. You'll simply need to locate the feature on the [Master Feature List](https://mattermost.productboar
```suggestion
Staying informed of status changes and comments on a feature is easy in ProductBoard. You'll need to

 1. Locate the feature on the [Master Feature List](https://mattermost.productboard.com/feature-board/1097524-master-feature-list)
 2. Open the feature details card by clicking on the feature name
 3. Add yourself as a follower by clicking on the `+` symbol on the bottom left side of the feature details card:
```

2020-06-04 20:22 UTC, jasonblais submitted a review, later dismissed

2020-06-04 20:23 UTC, jasonblais submitted a review, later dismissed

2020-06-05 08:57 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
> +Staying informed of status changes and comments on a feature is easy in ProductBoard. You'll need to
```suggestion
Staying informed of status changes and comments on a feature is easy in ProductBoard. You can:
```

2020-06-05 08:57 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
> + 1. Locate the feature on the [Master Feature List](https://mattermost.productboard.com/feature-board/1097524-master-feature-list)
```suggestion
 1. Locate the feature on the [Master Feature List](https://mattermost.productboard.com/feature-board/1097524-master-feature-list).
```

2020-06-05 08:58 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
> + 2. Open the feature details card by clicking on the feature name
```suggestion
 2. Click on the feature name to open the feature details card.
```

2020-06-05 08:59 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
> + 3. Add yourself as a follower by clicking on the `+` symbol on the bottom left side of the feature details card:
```suggestion
 3. Add yourself as a follower by clicking on the `+` symbol in the bottom left corner of the feature details card.
```

2020-06-05 09:00 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
>  As a **Contributor** in ProductBoard, you have access to view the [master feature list](https://mattermost.productboard.com/feature-board/1097524-master-feature-list). This is the view where the Prod
```suggestion
As a **Contributor** in ProductBoard, you have access to view the [master feature list](https://mattermost.productboard.com/feature-board/1097524-master-feature-list). This is the view where the Product team organizes and prioritizes new features and functionality that is being considered or planned for Mattermost. 

You can search and browse all features and ideas and even read the notes and portal cards from Product Managers for a detailed description of the feature/idea. In the case of planned features, you will have complete insight into the status of the feature and a rough idea of where it sits on the roadmap. 
```

2020-06-05 09:01 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
>  Within the detailed view of individual features, you can view the full list of insights added by other PMs, CSMs, SAs, or Support Managers. You will also have the option to add insight directly to th
```suggestion
Within the detailed view of individual features, you can view the full list of insights added by other PMs, CSMs, SAs, or Support Managers. You will also have the option to add insight directly to the feature itself.
```

2020-06-05 09:02 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
>  Using the official [ProductBoard Chrome Extension](https://chrome.google.com/webstore/detail/productboard-make-product/mlpbdkpkicfkhgagnoamdcimmhdkakni) you can easily add notes from any page within
```suggestion
Using the official [ProductBoard Chrome Extension](https://chrome.google.com/webstore/detail/productboard-make-product/mlpbdkpkicfkhgagnoamdcimmhdkakni) you can add notes from any page within Chrome (including SFDC, Zendesk, GitHub, HackerNews, Mattermost web, etc.) and streamline your workflow dramatically.
```

2020-06-05 09:03 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
>  New feedback from users and customers is sent to the [Insights Board](https://mattermost.productboard.com/insights). Typically these are submitted by product managers, support, customer success manag
```suggestion
New feedback from users and customers is sent to the [Insights Board](https://mattermost.productboard.com/insights). Typically these are submitted by Product Managers, Support, Customer Success Managers, or Sales through integrations with email, Zapier, Zendesk, or others.
```

2020-06-05 09:04 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
>  You can add a new note to capture feedback from a customer call. This is used to help identify customer problems, wants/needs, feature lack, and any other areas for improvement that stem from interac
```suggestion
You can add a new note to capture feedback from a customer call. This is used to help identify customer problems, wants/needs, feature shortcomings, and any other areas for improvement that stem from interacting with customers. Essentially, think of this as a place to communicate the most important takeaways from customer calls that the Product team can help you with. 
```

2020-06-05 09:04 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
>  * If you are not sure if the request or feedback should apply to an existing feature, you can simply capture the feedback as a note and assign to the PM overseeing that area (or just leave unassigned
```suggestion
* If you are not sure if the request or feedback should apply to an existing feature, you can simply capture the feedback as a note, assign it to the PM overseeing that area, or leave it unassigned.  
```

2020-06-05 09:05 UTC, justinegeffen commented on operations/research-and-development/product/product-planning/how-to-use-productboard.md
>  * If you are not sure if the request or feedback should apply to an existing feature, you can simply capture the feedback as a note and assign to the PM overseeing that area (or just leave unassigned
If it's left unassigned, how does it get picked up and prioritized?

2020-06-08 19:00 UTC, justinegeffen approved these changes
I've committed the editorial changes I suggested as they were punctuation, style, and formatting changes. The content looks great, thank you! :)

2020-06-08 19:05 UTC, jasonblais approved these changes

2020-06-08 19:05 UTC, merged