Create localization.md
mattermost/mattermost-handbook pull request #451
Opened 2020-09-14 20:44 UTC by justinegeffen

Moved Localization to handbook.

2020-09-14 22:35 UTC, jasonblais requested changes
Thanks! Please add to SUMMARY.md, below "help wanted tickets"

2020-09-15 11:46 UTC, jasonblais approved these changes, later dismissed

2020-09-15 12:23 UTC, amyblais commented on contributors/contributors/localization.md
> +If you're interested in contributing translations to Mattermost, please join the [Mattermost localization channel to discuss] (https://community.mattermost.com/core/channels/localization). Below are
Link here is broken

2020-09-15 13:39 UTC, justinegeffen commented on contributors/contributors/localization.md
> +If you're interested in contributing translations to Mattermost, please join the [Mattermost localization channel to discuss] (https://community.mattermost.com/core/channels/localization). Below are
```suggestion
If you're interested in contributing translations to Mattermost, please join the [Mattermost localization channel to discuss](https://community.mattermost.com/core/channels/localization). Below are descriptions of the overall localization process.
```

2020-09-15 14:15 UTC, justinegeffen commented on contributors/contributors/localization.md
> +If you're interested in contributing translations to Mattermost, please join the [Mattermost localization channel to discuss] (https://community.mattermost.com/core/channels/localization). Below are
Thanks, Amy, it's fixed. :)

2020-09-15 16:52 UTC, jasonblais approved these changes

2020-09-15 23:16 UTC, amyblais approved these changes

2020-09-16 04:35 UTC, merged