Add notes about release issues to Plugin Release Process
mattermost/mattermost-handbook pull request #487
Opened 2020-10-03 11:27 UTC by hanzei

#### Summary
Follow up on https://github.com/mattermost/mattermost-handbook/pull/479

2020-10-04 20:11 UTC, justinegeffen commented on operations/research-and-development/engineering/plugin-release-process.md
> +  * **Summary:** Add every outstand PR or issue as an item on as [taks list](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-task-lists).
```suggestion
  * **Summary:** Add every outstanding PR or issue as an item on as [task list](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-task-lists).
```

2020-10-04 20:11 UTC, justinegeffen submitted a review, later dismissed

2020-10-05 12:49 UTC, jfrerich commented
Oh great.  The plugin release process has a landing page in the handbook.  I'll do another PR to help clean the page up and then I can stop referencing my gitbook :)

2020-10-05 12:55 UTC, jfrerich requested changes, later dismissed

2020-10-05 12:55 UTC, jfrerich commented on operations/research-and-development/engineering/plugin-release-process.md
> +  * **Summary:** Add every outstanding PR or issue as an item on as [task list](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-task-lists).
```suggestion
  * **Summary:** Add every outstanding PR or issue as a [task list item](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-task-lists).
```

2020-10-05 12:55 UTC, jfrerich commented on operations/research-and-development/engineering/plugin-release-process.md
> +* Add that issue to the [Plugin Release board](https://github.com/orgs/mattermost/projects/2) in `Code Changes Needed`.
```suggestion
* Add that issue to the [Plugin Releases board](https://github.com/orgs/mattermost/projects/2) in `Code Changes Needed`.
```
For consistency with the actual board name.

2020-10-06 14:37 UTC, justinegeffen submitted a review, later dismissed

2020-10-07 12:50 UTC, justinegeffen approved these changes

2020-10-08 14:36 UTC, merged