Update and rename mattermost-communication.md
mattermost/mattermost-handbook pull request #508
Opened 2020-10-09 19:24 UTC by natalie-hub

Rename to to mattermost-communication-values.md
Also updated formatting and added additional text, bullets

#### Summary

2020-10-09 21:34 UTC, jasonblais approved these changes

2020-10-09 21:34 UTC, jasonblais requested changes
propose 'remote-only' -> 'remote-first'

2020-10-09 21:34 UTC, jasonblais commented on operations/workplace/mattermost-communication-values.md
> +As an open source, remote-only and communities-centered company, effective, efficient and courteous communication is expected of every team member. A few guidelines we live by:
```suggestion
As an open source, remote-first and communities-centered company, effective, efficient and courteous communication is expected of every team member. A few guidelines we live by:  
```

2020-10-12 23:33 UTC, hannaparks approved these changes

2020-10-13 23:17 UTC, natalie-hub reviewed
Thanks for the updates @jasonblais

2020-10-14 21:02 UTC, jasonblais approved these changes

2020-10-14 21:02 UTC, merged