WIP: Approved reviewers and permissions to handbook process
mattermost/mattermost-handbook pull request #54
Opened 2020-03-03 13:37 UTC by jasonblais

@michaelschiffmm This is a proposal for approved reviewers and permission levels. Would be interested to hear your thoughts for BizOps.

2020-03-06 18:25 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-update-handbook.md
> +2. Then, click the **Edit** pencil icon in the top right corner. This opens a Markdown formatted document of the page. To learn more about Markdown formatting, see the [Mattermost guide for formattin
```suggestion
2. In GitHub click the pencil icon in the navigation bar (above the page header) called **Edit the file in your fork of this project** to open the editable Markdown format page. 
- To learn more about Markdown formatting, see the [Mattermost guide for formatting text](https://docs.mattermost.com/help/messaging/formatting-text.html), or [the guide from GitBook](https://docs.gitbook.com/editing-content/markdown).
```

2020-03-06 18:28 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-update-handbook.md
> +3. Make your edits. When you're ready to submit your changes, scroll to the bottom of the page to commit your changes.
```suggestion
3. Make your edits. When you're ready to submit your changes, scroll to the bottom of the page to commit your changes and start a pull request.
```

2020-03-06 18:29 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-update-handbook.md
> +* Add a descriptive title and comments to summarize the changes made, then select **Create a new branch for this commit and start a pull request**.
```suggestion
* Add a descriptive title and comments to summarize the changes made.
```

2020-03-06 18:43 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-update-handbook.md
> +4. On the next page, scroll down to compare changes with the original document, request **Reviewers** on the top right navigation, select relevant [labels](https://developers.mattermost.com/contribut
```suggestion
4. On the next page, scroll down to compare changes with the original document and then select **Create pull request**. 

5. Confirm that the title and description are correct. Then select **Create pull request**.  
```

2020-03-06 18:45 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-update-handbook.md
>  Once a pull request has been submitted and the correct labels assigned, the review process begins. This includes aligning the content with the Style Guide, validating processes, and tagging any other
```suggestion
Once a pull request has been submitted, a core committer with write-access assigns relevant reviewers and labels to kick off the review process.  The review process includes aligning the content with the Style Guide, validating the changes, and tagging any other relevant committers.
```

2020-03-06 18:46 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-update-handbook.md
> +4. Staff contributors: Submits changes to handbook.mattermost.com via PRs. Have access to request reviews, add labels, submit PR reviews, and be requested reviews from.
```suggestion
4. Staff contributors: Submits changes to handbook.mattermost.com via PRs. Have access to request reviews, add labels, submit PR reviews, and be requested as reviewers.
```

2020-03-06 18:47 UTC, justinegeffen requested changes
I've reviewed the steps for a PR in the handbook and updated the process.

2020-03-06 22:37 UTC, jasonblais commented
Thank you! @justinegeffen editor suggestions applied

2020-03-11 22:08 UTC, jasonblais reviewed
I will revisit CLA process with HR following feedback from Schiff, and proving the granular permissions is in progress with Jason Deland. Merging given editor feedback applied, and we can iterate process further

2020-03-11 22:09 UTC, merged