Update .gitbook.yaml
mattermost/mattermost-handbook pull request #565
Opened 2020-12-02 14:27 UTC by justinegeffen

Fixed incorrect redirect formatting. Added new redirect based on 404 report in GA.

2020-12-02 14:58 UTC, jasonblais requested changes
Just one correction

2020-12-02 14:58 UTC, jasonblais commented on .gitbook.yaml
> +   contributors/onboarding/staff-on-boarding-guide: /operations/workplace/people/working-at-mattermost/onboarding.md
```suggestion
   contributors/onboarding/staff-on-boarding-guide: /operations/workplace/people/working-at-mattermost/onboarding/staff-onboarding-guide.md
```

2020-12-02 14:59 UTC, justinegeffen commented
Oh that's a good catch, thank you!

2020-12-11 17:08 UTC, jasonblais approved these changes

2020-12-11 17:08 UTC, merged