Update frequently-asked-questions.md
mattermost/mattermost-handbook pull request #575
Opened 2020-12-15 07:15 UTC by justinegeffen

Update based on: https://github.com/mattermost/docs/pull/4176

2020-12-15 13:08 UTC, amyblais commented
I'm assigning this to Carrie (Tech writer) but let me know if you need help.

2020-12-15 13:33 UTC, cwarnermm commented on contributors/onboarding/frequently-asked-questions.md
> +* Discuss with your manager the dates you plan to take off and decide who will be your backup.
```suggestion
* Discuss the dates you plan to take off with your manager, and decide who will be your backup.
```

2020-12-15 13:36 UTC, cwarnermm commented on contributors/onboarding/frequently-asked-questions.md
> +## I am planning to move, what do I need to know?
```suggestion
## I am planning to move. What do I need to know?
```

2020-12-15 13:38 UTC, cwarnermm requested changes
Minor suggestions provided inline. Very good read overall!

2020-12-15 14:11 UTC, cwarnermm approved these changes
Looks great! Thank you!

2021-01-14 07:37 UTC, justinegeffen commented
I'm merging this as there are no major content changes. @natalie-hub if there are any issues please let me know and I can open a new PR. :)

2021-01-14 07:37 UTC, merged