Update release-announcement.md
mattermost/mattermost-handbook pull request #647
Opened 2021-03-12 00:18 UTC by amyblais

2021-03-12 02:35 UTC, jasonblais requested changes
Just minor proposals, else looks good to me!

2021-03-12 02:35 UTC, jasonblais commented on operations/research-and-development/product/how-to-guides-for-product/release-announcement.md
> +* The PM-approved draft will be provided for review to the Product Marketing Director.
```suggestion
* The PM-approved draft will be provided for review to the Director of Product Marketing.
```

2021-03-12 02:35 UTC, jasonblais commented on operations/research-and-development/product/how-to-guides-for-product/release-announcement.md
> +* Release Manager provides an outline of the release announcement and deadlines for Product Managers, along with a heads-up for Jack that the blog post is coming.
```suggestion
* Release Manager provides an outline of the release announcement and deadlines for Product Managers, along with a heads-up for Director of Product Marketing that the blog post is coming.
```

2021-03-12 02:35 UTC, jasonblais commented on operations/research-and-development/product/how-to-guides-for-product/release-announcement.md
> +* Jason and Katie do a final review on the release announcement before handing it off to Jack.
```suggestion
* Product Management leads do a final review on the release announcement before handing it off to Director of Product Marketing.
```

2021-03-15 21:29 UTC, wiersgallak approved these changes, later dismissed
Thanks, Amy!

2021-04-21 13:08 UTC, jasonblais approved these changes

2021-04-21 13:09 UTC, merged