Create product-ownership-areas.md
mattermost/mattermost-handbook pull request #651
Opened 2021-03-24 03:39 UTC by wiersgallak

PM Areas of Ownership

#### Summary

2021-03-24 04:01 UTC, jasonblais requested changes

2021-03-24 04:01 UTC, jasonblais commented on operations/research-and-development/product/product-ownership-areas.md
> +For a comprehensive list of ownership areas, please see [this document](https://docs.google.com/spreadsheets/d/1-EUPdTpOxNx4bwf-312Pgqis7xSObK00c-KYwPXr2Y0/edit?usp=sharing).
Spreadsheet opens in "Sheet 3" tab which looks incomplete, do we want to open in the "Internal" tab?

2021-03-24 04:01 UTC, jasonblais commented on operations/research-and-development/product/product-ownership-areas.md
> +| Customer Journey (On-Prem) | Trials, Purchases/Customer Portal, In-product notices, Admin Adivsor, Licenses | Jason Blais |
Propose we combine customer journey on-prem + cloud into one row and note ownership breakdown in PM Owner column

2021-03-24 04:01 UTC, jasonblais commented on operations/research-and-development/product/product-ownership-areas.md
> +| Customer Journey (On-Prem) | Trials, Purchases/Customer Portal, In-product notices, Admin Adivsor, Licenses | Jason Blais |
```suggestion
| Customer Journey | Trials, Billing, Purchases/Customer Portal, In-product notices, Admin Advisor, Licenses | Jason Blais (Self-Managed), Katie Wiersgalla (Cloud) |
```

2021-03-24 15:11 UTC, wiersgallak commented on operations/research-and-development/product/product-ownership-areas.md
> +For a comprehensive list of ownership areas, please see [this document](https://docs.google.com/spreadsheets/d/1-EUPdTpOxNx4bwf-312Pgqis7xSObK00c-KYwPXr2Y0/edit?usp=sharing).
Good catch - removed my working sheet.

2021-03-24 15:17 UTC, jasonblais submitted a review, later dismissed

2021-03-24 15:31 UTC, cwarnermm reviewed
Non-blocking suggestions provided inline

2021-03-24 15:31 UTC, cwarnermm commented on operations/research-and-development/product/product-ownership-areas.md
> +| Customer Journey | Trials, Billing, Purchases/Customer Portal, In-product notices, Admin Advisor, Licenses | Jason Blais (Self-Managed), Katie Wiersgalla (Cloud) |
```suggestion
| Customer Journey | Trials, Billing, Purchases/Customer Portal, In-Product Notices, Admin Advisor, Licenses | Jason Blais (Self-Managed), Katie Wiersgalla (Cloud) |
```

2021-03-24 15:31 UTC, cwarnermm commented on operations/research-and-development/product/product-ownership-areas.md
> +| Administration | System Console, Compliance, Authentication, User and Team Management, Permissions| Adam Clarkson |
```suggestion
| Administration | System Console, Compliance, Authentication, User and Team Management, Permissions | Adam Clarkson |
```

2021-03-24 15:31 UTC, cwarnermm commented on operations/research-and-development/product/product-ownership-areas.md
> +| Platform | High Availabilty, Database, File Storage, Security, Logging, VPC Peering, Kubernetes, Omnibus | Katie Wiersgalla|
```suggestion
| Platform | High Availabilty, Database, File Storage, Security, Logging, VPC Peering, Kubernetes, Omnibus | Katie Wiersgalla |
```

2021-03-24 20:17 UTC, cwarnermm approved these changes
Looks great and reads well!

2021-03-25 14:26 UTC, wiersgallak commented
@jasonblais are you able to merge this PR?  I don't have access.

2021-03-25 14:55 UTC, merged