Update how-to-create-release-announcements.md
mattermost/mattermost-handbook pull request #66
Opened 2020-03-06 23:07 UTC by amyblais

I'm adding a step for myself to be the one who leads the team to arrive to a decision early in the process on what the main highlight / theme for a release blog post should be, and then stick to it.

Myself, marketing, PMs, etc. seem to be equally struggling to make this decision and don't seem to have strong opinions on what to highlight (or they don't speak up), or they have different views on what to highlight.

It seems we're often struggling to identify what we want to highlight, which then delays reviews, the Hero image, and essentially final CEO review.

Currently for v5.21 blog post we're changing what we want to highlight in the last minute, although a few days ago it seemed clear which topic is most impactful. Our information on the most impactful feature has suddenly changed. This shouldn't happen again.

Will still need to think about how this decision making should happen (during a call or in a channel with active participation from all parties), and whether we need guidelines for this decision. 

One big part is probably ensuring that we have all the information we need to arrive at the decision. 
 - If a feature is at risk of being cut, don't highlight it.
 - If a topic can be broken into separate sections and whether it has a larger impact than what it seems (which is happening with v5.21 blog post).
 - Has the feature been asked a lot / what is the overall impact.

2020-03-07 00:20 UTC, amyblais commented
This was already a problem during last release's v5.20 blog post, and it seems none of the process changes that we've made since then have helped mitigate this problem.

2020-03-11 22:11 UTC, jasonblais reviewed
I know this is WIP but happened to notice while reviewing handbook PRs

2020-03-11 22:12 UTC, jasonblais commented on operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
> +   3. **\(Author owns\)** Draft Tweet text for all screenshots included as well as for MVP winner
```suggestion
   3. **\(Author owns\)** Draft Tweet text for all screenshots and MVP winner included
```

2020-03-16 16:55 UTC, jasonblais requested changes
@amyblais Thanks! One minor proposal.

Not caused by this PR, but looks like all the screenshots are incorrect in this branch: https://github.com/mattermost/mattermost-handbook/blob/1497fdbd16ec44a16d6d157c562fd51df9328558/operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-screenshots-and-gifs.md#dos-and-donts

Instead they should be like here https://handbook.mattermost.com/operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-screenshots-and-gifs#dos-and-donts

Although not related to your changes here (this is related to GitBook), we'll need to fix them as otherwise they'll be incorrect as soon as this PR is merged. 

Can you help with that? It should be fixed by downloading the image from GitBook page and re-uploading at https://github.com/mattermost/mattermost-handbook/tree/0.2.1/.gitbook/assets

2020-03-16 16:55 UTC, jasonblais commented on operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-screenshots-and-gifs.md
> +  * Check that the font size is not too small.
```suggestion
  * All text should have large enough font size so that text is easily readable.
```

2020-03-16 16:55 UTC, jasonblais commented on operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-screenshots-and-gifs.md
> +  * Check that the font size is not too small.
^This is not worded properly..but basically the guideline is that if you can't easily read the text, the font size is too small

2020-03-18 19:08 UTC, amyblais commented
What does "downloading the image from GitBook page" mean?

2020-03-18 20:58 UTC, jasonblais commented
@amyblais Good question! If you right-click on an image in handbook, then select "Save Image As..", you can download the image and save it locally.

That way you can then upload the image to the `/assets` folder.

Sorry for the extra work as it's not caused by you, we are locking GitBook edits shortly to prevent this from happening in future. We just need to resolve last few permissions issues on this repo before we can do so (which are in progress)

2020-04-07 21:47 UTC, jasonblais approved these changes
@amyblais Was this waiting for me? Looks good to me, so merging, but let me know if it wasn't ready yet,

2020-04-07 21:47 UTC, merged

2020-04-07 21:52 UTC, amyblais commented
@jasonblais No it wasn't ready yet as I haven't updated the last image yet for How to create release announcements doc.

2020-04-07 21:56 UTC, jasonblais commented
Whoops, sorry..

2020-04-07 21:57 UTC, jasonblais commented
@amyblais I restored your branch (`amyblais-patch-1`) so you can resubmit the PR