manager-onboarding-1.md
mattermost/mattermost-handbook pull request #676
Opened 2021-04-16 01:22 UTC by natalie-hub

Updated Pre-day one instructions

#### Summary

2021-04-23 10:44 UTC, justinegeffen approved these changes, later dismissed

2021-04-23 16:34 UTC, lynn915 commented
Looks good! Can we update the systems checklist to the Onboarding in the IT Helpdesk (https://helpdesk.mattermost.com/support/home)? Thank you!

2021-04-23 16:35 UTC, lynn915 requested changes
Looks good! Can we change the "Systems Checklist Form" to 
"Complete the Onboarding Systems Form in the IT HelpDesk (https://helpdesk.mattermost.com/support/home) ? Thanks!

2021-04-28 09:08 UTC, justinegeffen approved these changes

2021-04-28 09:08 UTC, merged