Update how-to-update-handbook.md
mattermost/mattermost-handbook pull request #698
Opened 2021-05-11 18:06 UTC by justinegeffen

Changed heading capitalization. Removed 1x offboarded staff member.

2021-05-11 18:14 UTC, jasonblais commented on company/how-to-guides-for-staff/how-to-update-handbook.md
> -3. @rbradleyhaas: Signs off on changes to [business operations](https://handbook.mattermost.com/operations/business-operations).
Can you touch base with Kevin Fayle if he'd like to be the sign-off person? He's the new Dir of Marketing Ops and Analytics, and might like to have an opportunity to review.

He only started yesterday, but I don't foresee changes in the coming weeks that he'd have to review

2021-05-11 18:14 UTC, jasonblais requested changes
Just one comment above, otherwise no concerns

2021-05-11 18:22 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-update-handbook.md
> -3. @rbradleyhaas: Signs off on changes to [business operations](https://handbook.mattermost.com/operations/business-operations).
Good idea, and he's happy to do so. I've made that change. :)

2021-05-11 23:31 UTC, jasonblais requested changes

2021-05-11 23:31 UTC, jasonblais commented on company/how-to-guides-for-staff/how-to-update-handbook.md
> -3. @rbradleyhaas: Signs off on changes to [business operations](https://handbook.mattermost.com/operations/business-operations).
Sorry, I forgot the old BizOps section got removed via https://github.com/mattermost/mattermost-handbook/pull/687/files

For now, let's link to https://handbook.mattermost.com/operations/messaging-and-math/demand-generation-reporting instead

2021-05-11 23:31 UTC, jasonblais commented on company/how-to-guides-for-staff/how-to-update-handbook.md
> +3. @kevinfayle: Signs off on changes to [marketing ops and analytics](https://handbook.mattermost.com/operations/research-and-development/product/analytics).
```suggestion
3. @kevinfayle: Signs off on changes to [marketing ops and analytics](https://handbook.mattermost.com/operations/messaging-and-math/demand-generation-reporting).
```

2021-05-12 12:24 UTC, jasonblais approved these changes

2021-05-12 12:24 UTC, merged