Update mobile-feature-guidelines.md
mattermost/mattermost-handbook pull request #738
Opened 2021-06-04 18:46 UTC by amyblais

Based on suggestion https://community.mattermost.com/core/pl/x9aduew3stbofpsuz5fhkjk1cw, add a shortlist of features (e.g. SSO) that would require the feature to be released on mobile prior to Cloud to avoid a broken experience.

Let me know what other features should be listed here.

2021-06-04 19:21 UTC, wiersgallak approved these changes, later dismissed

2021-06-04 19:33 UTC, esethna requested changes

2021-06-04 19:33 UTC, esethna commented on operations/research-and-development/product/development-process/mobile-feature-guidelines.md
> +- If a new feature is related to Single Sign-On (SSO), plan to release the feature on Mobile Apps prior to Cloud to avoid users from being blocked from using the Mobile Apps.
I would generalize this even more to say anything related to authentication (ie if a user would be unable to login into the mobile app without the changes being present)

2021-06-04 20:41 UTC, esethna approved these changes

2021-06-07 13:01 UTC, jasonblais approved these changes

2021-06-07 13:48 UTC, merged