Update README.md
mattermost/mattermost-handbook pull request #758
Opened 2021-06-12 08:39 UTC by justinegeffen

Updated VP Finance.

2021-06-12 08:47 UTC, justinegeffen commented on operations/operations/company-agreements.md
> +**Note: Pull Requests for updates to this page need to be signed off by both VP Finance and CEO in the PR process.**
```suggestion
**Note: Pull Requests for updates to this page need to be signed off by both VP Finance & Operations and CEO in the PR process.**
```

2021-06-12 08:48 UTC, justinegeffen commented on operations/operations/company-agreements.md
> +Company agreements should only be signed by CEO, Ian Tien, or VP Finance, Tim Quock with the following exceptions:
```suggestion
Company agreements should only be signed by CEO, Ian Tien, or VP Finance & Operations, Tim Quock with the following exceptions:
```

2021-06-12 08:48 UTC, justinegeffen commented on operations/operations/company-agreements.md
> +* The following agreements may also be signed by the VP Finance, Tim Quock.
```suggestion
* The following agreements may also be signed by the VP Finance & Operations, Tim Quock.
```

2021-06-12 08:48 UTC, justinegeffen commented on operations/operations/mlt-cadence/README.md
> +* Tim Quock: VP, Finance
```suggestion
* Tim Quock: VP, Finance & Operations
```

2021-06-12 13:48 UTC, jasonblais requested changes
@justinegeffen Tim's title is in fact `VP, Finance`

2021-06-12 16:13 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-purchase/how-to-procure-a-vendor-contract.md
> +All contracts are to address either Ian Tien \(CEO\) or Time Quock \(VP Finance & Operations\), and should include the following relevant information:
```suggestion
All contracts are to address either Ian Tien \(CEO\) or Time Quock \(VP Finance\), and should include the following relevant information:
```

2021-06-12 16:14 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-purchase/how-to-procure-a-vendor-contract.md
> +All contracts are to address either Ian Tien \(CEO\) or Time Quock \(VP Finance & Operations\), and should include the following relevant information:
```suggestion
All contracts are to address either Ian Tien \(CEO\) or Tim Quock \(VP Finance\), and should include the following relevant information:
```

2021-06-12 16:14 UTC, justinegeffen commented on company/how-to-guides-for-staff/how-to-purchase/how-to-procure-a-vendor-contract.md
> +3. Contract sent to VP Finance & Operations or CEO for final signature in DocuSign.
```suggestion
3. Contract sent to VP Finance or CEO for final signature in DocuSign.
```

2021-06-12 16:14 UTC, justinegeffen commented on contributors/join-us/staff-recruiting/README.md
> +Hiring plans are created twice a year, and reviewed every quarter. Hiring Managers and department leads can request additional headcount by completing a [New Requisition ID Request Form](https://form
```suggestion
Hiring plans are created twice a year, and reviewed every quarter. Hiring Managers and department leads can request additional headcount by completing a [New Requisition ID Request Form](https://forms.gle/ewYXCm1FZPAb6Pyr6). As part of this request form and only for non-backfill roles, Hiring Managers will be asked to submit an [Issue/Solution Proposal](https://handbook.mattermost.com/operations/operations/company-processes/issue-solution). Finance assigns all requisition IDs and the CEO (Ian Tien) and VP Finance (Tim Quock) will need to approve ISP ahead of a new requisition ID assignment.
```

2021-06-12 16:15 UTC, justinegeffen commented on operations/finance/README.md
> +* Tim Quock, VP of Finance and Operations
```suggestion
* Tim Quock, VP of Finance
```

2021-06-12 16:16 UTC, justinegeffen commented on operations/operations/company-agreements.md
> +**Note: Pull Requests for updates to this page need to be signed off by both VP Finance & Operations and CEO in the PR process.**
```suggestion
**Note: Pull Requests for updates to this page need to be signed off by both VP Finance and CEO in the PR process.**
```

2021-06-12 16:16 UTC, justinegeffen commented on operations/operations/company-agreements.md
> +Company agreements should only be signed by CEO, Ian Tien, or VP Finance & Operations, Tim Quock with the following exceptions:
```suggestion
Company agreements should only be signed by CEO, Ian Tien, or VP Finance, Tim Quock, with the following exceptions:
```

2021-06-12 16:16 UTC, justinegeffen commented on operations/operations/company-agreements.md
> +* The following agreements may also be signed by the VP Finance & Operations, Tim Quock.
```suggestion
* The following agreements may also be signed by the VP Finance, Tim Quock.
```

2021-06-12 16:17 UTC, justinegeffen commented on operations/operations/mlt-cadence/README.md
> +* Tim Quock: VP, Finance & Operations
```suggestion
* Tim Quock: VP, Finance
```

2021-06-12 16:17 UTC, justinegeffen commented on operations/operations/company-policies/community-response-policy.md
> +* VP Finance & Operations: Tim Quock
```suggestion
* VP Finance: Tim Quock
```

2021-06-12 22:33 UTC, jasonblais submitted a review, later dismissed

2021-06-17 13:16 UTC, justinegeffen commented
@TQuock, @it33, following up on this for your approval as per the Handbook. Thank you! :)

2021-06-21 15:14 UTC, jasonblais approved these changes

2021-06-21 15:14 UTC, jasonblais commented
@justinegeffen Approved on Tim and Ian's behalf

2021-06-21 15:19 UTC, merged